import { mockExecFn, mockPipelineExecRuntime } from "@callumvass/forgeflow-shared/testing";
import { describe, expect, it } from "vitest";
import { listOpenAutoGeneratedIssueNumbers, readGitHubIssue } from "./index.js";

describe("repository GitHub issue transport", () => {
  it("reads a GitHub issue title and body through the repository boundary", async () => {
    const runtime = mockPipelineExecRuntime({
      cwd: "/tmp/project",
      execSafeFn: mockExecFn({
        "gh issue view 42": JSON.stringify({ number: 42, title: "Repo issue", body: "Issue body" }),
      }),
    });

    await expect(readGitHubIssue(42, runtime)).resolves.toEqual({
      number: 42,
      title: "Repo issue",
      body: "Issue body",
    });
  });

  it("lists open auto-generated GitHub issue numbers through the repository boundary", async () => {
    const runtime = mockPipelineExecRuntime({
      cwd: "/tmp/project",
      execSafeFn: mockExecFn({
        "gh issue list": JSON.stringify([{ number: 10 }, { number: 12 }]),
      }),
    });

    await expect(listOpenAutoGeneratedIssueNumbers(runtime)).resolves.toEqual([10, 12]);
  });
});
