import type { PipelineExecRuntime } from "../runtime/pipeline-context/exec.js";

export type RepositoryExecRuntime = Pick<PipelineExecRuntime, "cwd" | "execFn" | "execSafeFn">;
type ExecRuntime = Pick<RepositoryExecRuntime, "cwd" | "execFn">;
type SafeExecRuntime = Pick<RepositoryExecRuntime, "cwd" | "execSafeFn">;

export type ReviewTarget =
  | { kind: "pr"; prNumber: string }
  | { kind: "branch"; branch: string }
  | { kind: "current"; prNumber?: string };

export interface GitHubIssueDetails {
  number: number;
  title: string;
  body: string;
}

function parseJson(raw: string): unknown | null {
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function isGitHubIssueDetails(value: unknown): value is GitHubIssueDetails {
  return (
    typeof value === "object" &&
    value != null &&
    typeof (value as { number?: unknown }).number === "number" &&
    typeof (value as { title?: unknown }).title === "string" &&
    typeof (value as { body?: unknown }).body === "string"
  );
}

function splitLines(output: string): string[] {
  return output
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
}

async function checkoutPullRequest(prNumber: string, runtime: ExecRuntime): Promise<void> {
  await runtime.execFn(`gh pr checkout ${prNumber}`, runtime.cwd);
}

async function readPrBaseRef(prNumber: string, runtime: SafeExecRuntime): Promise<string | undefined> {
  const baseRef = (
    await runtime.execSafeFn(`gh pr view ${prNumber} --json baseRefName --jq .baseRefName`, runtime.cwd)
  ).trim();
  return baseRef || undefined;
}

async function ensureBranchAvailable(branch: string, runtime: ExecRuntime): Promise<void> {
  const quotedBranch = JSON.stringify(branch);
  const quotedRemoteBranch = JSON.stringify(`origin/${branch}`);

  await runtime.execFn(`git fetch origin ${quotedBranch} 2>/dev/null || true`, runtime.cwd);
  await runtime.execFn(
    `git checkout ${quotedBranch} 2>/dev/null || git checkout -b ${quotedBranch} --track ${quotedRemoteBranch}`,
    runtime.cwd,
  );
}

async function listChangedFilesAgainstBaseRef(baseRef: string, runtime: SafeExecRuntime): Promise<string[]> {
  const quotedBaseRef = JSON.stringify(baseRef);
  const quotedRemoteBaseRef = JSON.stringify(`origin/${baseRef}`);

  await runtime.execSafeFn(`git fetch origin ${quotedBaseRef} 2>/dev/null || true`, runtime.cwd);
  return splitLines(await runtime.execSafeFn(`git diff --name-only ${quotedRemoteBaseRef}...HEAD`, runtime.cwd));
}

export async function readCurrentPrNumber(runtime: SafeExecRuntime): Promise<string | undefined> {
  const prNumber = (await runtime.execSafeFn("gh pr view --json number --jq .number", runtime.cwd)).trim();
  return prNumber || undefined;
}

export async function listChangedFilesAgainstMain(runtime: SafeExecRuntime): Promise<string[]> {
  return splitLines(await runtime.execSafeFn("git diff --name-only main...HEAD", runtime.cwd));
}

export async function readUnifiedDiffAgainstMain(runtime: ExecRuntime): Promise<string> {
  return runtime.execFn("git diff main...HEAD", runtime.cwd);
}

export async function readReviewDiff(target: ReviewTarget, runtime: ExecRuntime): Promise<string> {
  if (target.kind === "pr") {
    await checkoutPullRequest(target.prNumber, runtime);
    return runtime.execFn(`gh pr diff ${target.prNumber}`, runtime.cwd);
  }

  if (target.kind === "branch") {
    await ensureBranchAvailable(target.branch, runtime);
  }

  return readUnifiedDiffAgainstMain(runtime);
}

export async function readRepositoryNameWithOwner(runtime: ExecRuntime): Promise<string> {
  return runtime.execFn("gh repo view --json nameWithOwner --jq .nameWithOwner", runtime.cwd);
}

export async function resolveReviewChangedFiles(
  target: ReviewTarget,
  runtime: RepositoryExecRuntime,
): Promise<string[]> {
  if (target.kind === "pr") {
    await checkoutPullRequest(target.prNumber, runtime);
    const changedFiles = await listChangedFilesAgainstMain(runtime);
    if (changedFiles.length > 0) return changedFiles;

    const baseRef = await readPrBaseRef(target.prNumber, runtime);
    return baseRef ? listChangedFilesAgainstBaseRef(baseRef, runtime) : [];
  }

  if (target.kind === "branch") {
    await ensureBranchAvailable(target.branch, runtime);
  }

  return listChangedFilesAgainstMain(runtime);
}

export async function listTrackedFiles(runtime: SafeExecRuntime): Promise<string[]> {
  return splitLines(await runtime.execSafeFn("git ls-files", runtime.cwd));
}

export async function listOpenAutoGeneratedIssueNumbers(runtime: SafeExecRuntime): Promise<number[] | null> {
  const raw = await runtime.execSafeFn(
    'gh issue list --state open --label "auto-generated" --limit 500 --json number',
    runtime.cwd,
  );
  if (!raw.trim()) return null;

  const parsed = parseJson(raw);
  if (!Array.isArray(parsed)) return null;
  return parsed.flatMap((item) =>
    typeof item === "object" && item != null && typeof (item as { number?: unknown }).number === "number"
      ? [(item as { number: number }).number]
      : [],
  );
}

export async function readGitHubIssue(
  issueNumber: number,
  runtime: SafeExecRuntime,
): Promise<GitHubIssueDetails | null> {
  const raw = await runtime.execSafeFn(`gh issue view ${issueNumber} --json number,title,body`, runtime.cwd);
  if (!raw.trim()) return null;

  const parsed = parseJson(raw);
  return isGitHubIssueDetails(parsed) ? parsed : null;
}
