import {
  emptyStage,
  type PipelineContext,
  pipelineResult,
  toAgentOpts,
  withRunLifecycle,
} from "@callumvass/forgeflow-shared/pipeline";
import { promptBootstrapPrd } from "../prd/bootstrap.js";
import { prdExists } from "../prd/document.js";
import { captureAutoGeneratedIssueSnapshot, validateNewAutoGeneratedIssues } from "./issue-creation/validation.js";

export async function runInit(pctx: PipelineContext) {
  return withRunLifecycle(pctx, "init", (innerPctx) => runInitInner(innerPctx));
}

async function maybeCreateBootstrapIssue(pctx: PipelineContext) {
  const { ctx } = pctx;
  if (!ctx.hasUI) return { created: false as const };

  const action = await ctx.ui.select("Create the initial bootstrap issue now?", [
    "Create bootstrap issue",
    "Skip for now",
  ]);
  if (action !== "Create bootstrap issue") return { created: false as const };

  const stages = [emptyStage("gh-single-issue-creator")];
  const opts = toAgentOpts(pctx, { stages, pipeline: "init" });
  const beforeSnapshot = await captureAutoGeneratedIssueSnapshot(pctx.cwd, pctx.execSafeFn);

  await pctx.runAgentFn(
    "gh-single-issue-creator",
    [
      "Read PRD.md and `.forgeflow/BOOTSTRAP.md` before drafting.",
      "Create exactly one initial scaffold/bootstrap GitHub issue for this blank project.",
      "Preserve every locked input from `.forgeflow/BOOTSTRAP.md` where relevant, including exact package manager choices, starter/template identifiers, scaffold commands, versioned tooling choices, and explicit use/avoid constraints.",
      "Do NOT generalise, normalise, or substitute those locked inputs.",
      "Keep the issue narrowly focused on the chosen baseline scaffold plus the first reusable feature/domain boundary.",
      "Do NOT include the first substantive product feature.",
    ].join(" "),
    opts,
  );

  const validationErrors = await validateNewAutoGeneratedIssues(pctx.cwd, pctx.execSafeFn, beforeSnapshot);
  if (validationErrors.length > 0) {
    return {
      created: false as const,
      stages,
      error: `Bootstrap issue creation failed validation:\n- ${validationErrors.join("\n- ")}`,
    };
  }

  const afterSnapshot = await captureAutoGeneratedIssueSnapshot(pctx.cwd, pctx.execSafeFn);
  const createdNumbers =
    beforeSnapshot == null || afterSnapshot == null
      ? []
      : [...afterSnapshot.numbers].filter((n) => !beforeSnapshot.numbers.has(n)).sort((a, b) => a - b);

  return {
    created: true as const,
    stages,
    issueNumber: createdNumbers[0],
  };
}

async function runInitInner(pctx: PipelineContext) {
  if (prdExists(pctx.cwd)) {
    return pipelineResult("PRD.md already exists. Run /prd-qa to refine it.", "init", []);
  }

  if (!pctx.ctx.hasUI) {
    return pipelineResult(
      "PRD.md not found. /init requires interactive mode, or you can create PRD.md manually and then run /prd-qa.",
      "init",
      [],
    );
  }

  const created = await promptBootstrapPrd(pctx, {
    confirmationTitle: "Create an initial PRD draft now?",
  });

  if (!created) {
    return pipelineResult("PRD initialisation cancelled.", "init", []);
  }

  const bootstrapIssue = await maybeCreateBootstrapIssue(pctx);
  if ("error" in bootstrapIssue && bootstrapIssue.error) {
    return pipelineResult(
      `Initial PRD draft and bootstrap constraints created, but ${bootstrapIssue.error}`,
      "init",
      bootstrapIssue.stages ?? [],
      true,
    );
  }

  if (bootstrapIssue.created) {
    const issueRef = bootstrapIssue.issueNumber ? ` #${bootstrapIssue.issueNumber}` : "";
    return pipelineResult(
      `Initial PRD draft and bootstrap constraints created. Next: review bootstrap issue${issueRef}, run /implement${issueRef}, then run /continue after the bootstrap slice lands.`,
      "init",
      bootstrapIssue.stages,
    );
  }

  return pipelineResult(
    "Initial PRD draft and bootstrap constraints created. Next: review PRD.md and .forgeflow/BOOTSTRAP.md. You can create the bootstrap issue now or later, then run /continue after the bootstrap slice lands.",
    "init",
    [],
  );
}
