import {
  emptyStage,
  type PipelineContext,
  pipelineResult,
  toAgentOpts,
  withRunLifecycle,
} from "@callumvass/forgeflow-shared/pipeline";
import { missingPrdResult, prdExists } from "../../prd/index.js";
import { captureAutoGeneratedIssueSnapshot, validateNewAutoGeneratedIssues } from "./validation.js";

export async function runCreateIssue(idea: string, pctx: PipelineContext) {
  return withRunLifecycle(pctx, "create-gh-issue", (innerPctx) => runCreateIssueInner(idea, innerPctx));
}

async function runCreateIssueInner(idea: string, pctx: PipelineContext) {
  const { ctx } = pctx;
  // Ask for feature idea interactively if not provided
  if (!idea && ctx.hasUI) {
    const input = await ctx.ui.input("Feature idea?", "");
    idea = input?.trim() ?? "";
  }
  if (!idea) {
    return pipelineResult("No feature idea provided.", "create-issue", []);
  }

  const stages = [emptyStage("gh-single-issue-creator")];
  const opts = toAgentOpts(pctx, { stages, pipeline: "create-issue" });
  const beforeSnapshot = await captureAutoGeneratedIssueSnapshot(pctx.cwd, pctx.execSafeFn);

  await pctx.runAgentFn("gh-single-issue-creator", idea, opts);

  const validationErrors = await validateNewAutoGeneratedIssues(pctx.cwd, pctx.execSafeFn, beforeSnapshot);
  if (validationErrors.length > 0) {
    return pipelineResult(
      `Issue creation failed validation:\n- ${validationErrors.join("\n- ")}`,
      "create-issue",
      stages,
      true,
    );
  }

  return pipelineResult("Issue created.", "create-issue", stages);
}

export async function runCreateIssues(pctx: PipelineContext) {
  return withRunLifecycle(pctx, "create-gh-issues", (innerPctx) => runCreateIssuesInner(innerPctx));
}

async function runCreateIssuesInner(pctx: PipelineContext) {
  if (!prdExists(pctx.cwd)) return missingPrdResult("create-issues");

  const stages = [emptyStage("gh-issue-creator")];
  const opts = toAgentOpts(pctx, { stages, pipeline: "create-issues" });
  const beforeSnapshot = await captureAutoGeneratedIssueSnapshot(pctx.cwd, pctx.execSafeFn);

  await pctx.runAgentFn(
    "gh-issue-creator",
    "Decompose PRD.md into vertical-slice GitHub issues. Treat the chosen options in ## Technical Direction as binding for issue guidance. If `.forgeflow/BOOTSTRAP.md` exists, read it and treat its locked inputs as binding too: preserve exact starter/template identifiers, package manager choices, scaffold commands, versioned tooling choices, and explicit use/avoid constraints where relevant. Treat ## Alternatives Considered as explanatory context only. Read the issue-template skill for the standard format. In greenfield or nearly empty repos, create exactly one explicit initial scaffold/bootstrap issue first, make it the only dependency-free issue, and then create feature slices that depend directly or transitively on it. That scaffold issue must still establish a real feature or domain boundary rather than treating generic roots such as src/, app/, server/, client/, test/, or tests/ as owning boundaries.",
    opts,
  );

  const validationErrors = await validateNewAutoGeneratedIssues(pctx.cwd, pctx.execSafeFn, beforeSnapshot);
  if (validationErrors.length > 0) {
    return pipelineResult(
      `Issue creation failed validation:\n- ${validationErrors.join("\n- ")}`,
      "create-issues",
      stages,
      true,
    );
  }

  return pipelineResult("Issue creation complete.", "create-issues", stages);
}
