import type { ExecFn } from "@callumvass/forgeflow-shared/pipeline";
import {
  listOpenAutoGeneratedIssueNumbers,
  listTrackedFiles,
  readGitHubIssue,
} from "@callumvass/forgeflow-shared/repository";

const GENERIC_ROOTS = new Set(["src", "test", "tests", "app", "server", "client"]);

interface CreatedIssueDetails {
  number: number;
  title: string;
  body: string;
}

interface IssueSnapshot {
  numbers: Set<number>;
}

function extractSection(body: string, heading: string): string | null {
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = body.match(new RegExp(`^## ${escaped}\\n([\\s\\S]*?)(?=^## |$)`, "m"));
  return match?.[1] ?? null;
}

function cleanPathValue(value: string): string {
  return value
    .trim()
    .replace(/^`+|`+$/g, "")
    .replace(/^['"]+|['"]+$/g, "");
}

function finalPathSegment(value: string): string | null {
  const cleaned = cleanPathValue(value).replace(/^\.\//, "").replace(/\/+$/g, "");
  if (!cleaned) return null;
  const segments = cleaned.split("/").filter(Boolean);
  if (segments.length === 0) return null;
  return segments[segments.length - 1]?.toLowerCase() ?? null;
}

function extractDependencies(body: string): number[] {
  const dependencies = extractSection(body, "Dependencies");
  if (dependencies == null) return [];
  return [...dependencies.matchAll(/#(\d+)/g)].map((match) => parseInt(match[1] ?? "0", 10)).filter(Number.isFinite);
}

function hasScaffoldTitle(title: string): boolean {
  return /\b(scaffold|bootstrap)\b/i.test(title);
}

function formatIssueNumbers(numbers: number[]): string {
  return numbers.length > 0 ? numbers.map((number) => `#${number}`).join(", ") : "none";
}

function isImplementationFile(path: string): boolean {
  const lower = path.trim().toLowerCase();
  if (!lower) return false;
  if (/(^|\/)(src|app|server|client|lib|test|tests|spec|specs|cmd|pkg|internal)\//.test(lower)) return true;
  return /\.(ts|tsx|js|jsx|mjs|cjs|py|rb|go|rs|java|kt|cs|ex|exs|php|swift|scala|vue|svelte)$/.test(lower);
}

async function repoLooksGreenfield(cwd: string, execSafeFn: ExecFn): Promise<boolean> {
  const trackedFiles = await listTrackedFiles({ cwd, execSafeFn });
  if (trackedFiles.length === 0) return false;
  return trackedFiles.every((file) => !isImplementationFile(file));
}

function validateGreenfieldIssueSet(issues: CreatedIssueDetails[]): string[] {
  if (issues.length === 0) return [];

  const sorted = [...issues].sort((a, b) => a.number - b.number);
  const firstIssue = sorted[0];
  if (firstIssue == null) return [];
  const dependenciesByIssue = new Map(sorted.map((issue) => [issue.number, extractDependencies(issue.body)]));
  const dependencyFreeIssues = sorted.filter((issue) => (dependenciesByIssue.get(issue.number) ?? []).length === 0);
  const errors: string[] = [];

  if (!hasScaffoldTitle(firstIssue.title)) {
    errors.push(
      `greenfield repos must start with an explicit scaffold/bootstrap issue; lowest new issue #${firstIssue.number} "${firstIssue.title}" should use "scaffold" or "bootstrap" in the title`,
    );
  }

  if (dependencyFreeIssues.length !== 1 || dependencyFreeIssues[0]?.number !== firstIssue.number) {
    errors.push(
      `greenfield repos must have exactly one dependency-free issue and it must be the initial scaffold issue; found ${formatIssueNumbers(dependencyFreeIssues.map((issue) => issue.number))}`,
    );
  }

  const reachesInitialScaffold = (issueNumber: number, seen = new Set<number>()): boolean => {
    if (issueNumber === firstIssue.number) return true;
    if (seen.has(issueNumber)) return false;
    seen.add(issueNumber);

    const dependencies = dependenciesByIssue.get(issueNumber) ?? [];
    return dependencies.some(
      (dependency) =>
        dependency === firstIssue.number ||
        (dependenciesByIssue.has(dependency) && reachesInitialScaffold(dependency, seen)),
    );
  };

  const disconnectedIssues = sorted
    .slice(1)
    .filter((issue) => !reachesInitialScaffold(issue.number))
    .map((issue) => issue.number);
  if (disconnectedIssues.length > 0) {
    errors.push(
      `greenfield repos must make later issues depend directly or transitively on the initial scaffold issue #${firstIssue.number}; missing dependency path for ${formatIssueNumbers(disconnectedIssues)}`,
    );
  }

  return errors;
}

export function validateIssueDraft(body: string): string[] {
  const errors: string[] = [];

  if (!/^## Structural Placement\b/m.test(body)) {
    errors.push("missing `## Structural Placement` section");
  }
  if (!/^## TDD Rehearsal\b/m.test(body)) {
    errors.push("missing `## TDD Rehearsal` section");
  }

  const owningMatches = [...body.matchAll(/^- Owning boundary:\s*(.+)$/gm)];
  if (owningMatches.length !== 1) {
    errors.push(`expected exactly one \`Owning boundary\` entry, found ${owningMatches.length}`);
  }

  const entryMatches = [...body.matchAll(/^- Public entry point:\s*(.+)$/gm)];
  if (entryMatches.length !== 1) {
    errors.push(`expected exactly one \`Public entry point\` entry, found ${entryMatches.length}`);
  }

  if (!/^- Files in scope:\s*(.+)$/m.test(body)) {
    errors.push("missing `Files in scope` entry in `## Structural Placement`");
  }
  if (!/^- Out of scope:\s*(.+)$/m.test(body)) {
    errors.push("missing `Out of scope` entry in `## Structural Placement`");
  }

  const owningBoundary = owningMatches[0]?.[1];
  if (owningBoundary) {
    const finalSegment = finalPathSegment(owningBoundary);
    if (finalSegment != null && GENERIC_ROOTS.has(finalSegment)) {
      errors.push(
        `owning boundary \`${cleanPathValue(owningBoundary)}\` ends at generic root \`${finalSegment}/\`; choose a feature or domain folder beneath it`,
      );
    }
  }

  const testPlan = extractSection(body, "Test Plan");
  if (testPlan == null) {
    errors.push("missing `## Test Plan` section");
  } else {
    const firstChecklist = testPlan.match(/^- \[ \] (.+)$/m)?.[1]?.trim();
    if (!firstChecklist) {
      errors.push("missing checklist entries in `## Test Plan`");
    } else if (!firstChecklist.startsWith("Trigger:")) {
      errors.push("first `## Test Plan` item must start with `Trigger:`");
    }
  }

  return errors;
}

async function readIssueSnapshot(cwd: string, execSafeFn: ExecFn): Promise<IssueSnapshot | null> {
  const numbers = await listOpenAutoGeneratedIssueNumbers({ cwd, execSafeFn });
  if (numbers == null) return null;
  return { numbers: new Set(numbers) };
}

async function readIssueDetails(
  cwd: string,
  issueNumber: number,
  execSafeFn: ExecFn,
): Promise<{ title: string; body: string } | null> {
  const details = await readGitHubIssue(issueNumber, { cwd, execSafeFn });
  if (details == null) return null;
  return { title: details.title, body: details.body };
}

export async function captureAutoGeneratedIssueSnapshot(
  cwd: string,
  execSafeFn: ExecFn,
): Promise<IssueSnapshot | null> {
  return readIssueSnapshot(cwd, execSafeFn);
}

export async function validateNewAutoGeneratedIssues(
  cwd: string,
  execSafeFn: ExecFn,
  beforeSnapshot: IssueSnapshot | null,
): Promise<string[]> {
  if (beforeSnapshot == null) {
    return ["could not capture the pre-creation `auto-generated` issue snapshot through the repository boundary"];
  }

  const afterSnapshot = await readIssueSnapshot(cwd, execSafeFn);
  if (afterSnapshot == null) {
    return ["could not capture the post-creation `auto-generated` issue snapshot through the repository boundary"];
  }

  const createdNumbers = [...afterSnapshot.numbers].filter((n) => !beforeSnapshot.numbers.has(n)).sort((a, b) => a - b);
  if (createdNumbers.length === 0) return [];

  const failures: string[] = [];
  const createdIssues: CreatedIssueDetails[] = [];
  for (const issueNumber of createdNumbers) {
    const details = await readIssueDetails(cwd, issueNumber, execSafeFn);
    if (details == null) {
      failures.push(`#${issueNumber}: could not read issue body through the repository boundary`);
      continue;
    }

    createdIssues.push({ number: issueNumber, title: details.title, body: details.body });

    const errors = validateIssueDraft(details.body);
    if (errors.length === 0) continue;

    failures.push(`#${issueNumber} ${details.title}: ${errors.join("; ")}`);
  }

  if (await repoLooksGreenfield(cwd, execSafeFn)) {
    failures.push(...validateGreenfieldIssueSet(createdIssues));
  }

  return failures;
}
