import type { ExecFn } from "@callumvass/forgeflow-shared/pipeline";

const GENERIC_ROOTS = new Set(["src", "test", "tests", "app", "server", "client"]);

interface IssueListEntry {
  number?: unknown;
}

interface IssueDetails {
  number?: unknown;
  title?: unknown;
  body?: unknown;
}

interface IssueSnapshot {
  numbers: Set<number>;
}

function extractSection(body: string, heading: string): string | null {
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = body.match(new RegExp(`^## ${escaped}\\n([\\s\\S]*?)(?=^## |$)`, "m"));
  return match?.[1] ?? null;
}

function cleanPathValue(value: string): string {
  return value
    .trim()
    .replace(/^`+|`+$/g, "")
    .replace(/^['"]+|['"]+$/g, "");
}

function finalPathSegment(value: string): string | null {
  const cleaned = cleanPathValue(value).replace(/^\.\//, "").replace(/\/+$/g, "");
  if (!cleaned) return null;
  const segments = cleaned.split("/").filter(Boolean);
  if (segments.length === 0) return null;
  return segments[segments.length - 1]?.toLowerCase() ?? null;
}

export function validateIssueDraft(body: string): string[] {
  const errors: string[] = [];

  if (!/^## Structural Placement\b/m.test(body)) {
    errors.push("missing `## Structural Placement` section");
  }
  if (!/^## TDD Rehearsal\b/m.test(body)) {
    errors.push("missing `## TDD Rehearsal` section");
  }

  const owningMatches = [...body.matchAll(/^- Owning boundary:\s*(.+)$/gm)];
  if (owningMatches.length !== 1) {
    errors.push(`expected exactly one \`Owning boundary\` entry, found ${owningMatches.length}`);
  }

  const entryMatches = [...body.matchAll(/^- Public entry point:\s*(.+)$/gm)];
  if (entryMatches.length !== 1) {
    errors.push(`expected exactly one \`Public entry point\` entry, found ${entryMatches.length}`);
  }

  if (!/^- Files in scope:\s*(.+)$/m.test(body)) {
    errors.push("missing `Files in scope` entry in `## Structural Placement`");
  }
  if (!/^- Out of scope:\s*(.+)$/m.test(body)) {
    errors.push("missing `Out of scope` entry in `## Structural Placement`");
  }

  const owningBoundary = owningMatches[0]?.[1];
  if (owningBoundary) {
    const finalSegment = finalPathSegment(owningBoundary);
    if (finalSegment != null && GENERIC_ROOTS.has(finalSegment)) {
      errors.push(
        `owning boundary \`${cleanPathValue(owningBoundary)}\` ends at generic root \`${finalSegment}/\`; choose a feature or domain folder beneath it`,
      );
    }
  }

  const testPlan = extractSection(body, "Test Plan");
  if (testPlan == null) {
    errors.push("missing `## Test Plan` section");
  } else {
    const firstChecklist = testPlan.match(/^- \[ \] (.+)$/m)?.[1]?.trim();
    if (!firstChecklist) {
      errors.push("missing checklist entries in `## Test Plan`");
    } else if (!firstChecklist.startsWith("Trigger:")) {
      errors.push("first `## Test Plan` item must start with `Trigger:`");
    }
  }

  return errors;
}

function parseIssueList(raw: string): Set<number> | null {
  if (!raw.trim()) return null;
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (!Array.isArray(parsed)) return null;

  const numbers = new Set<number>();
  for (const item of parsed as IssueListEntry[]) {
    if (typeof item.number === "number") numbers.add(item.number);
  }
  return numbers;
}

async function readIssueSnapshot(cwd: string, execSafeFn: ExecFn): Promise<IssueSnapshot | null> {
  const raw = await execSafeFn('gh issue list --state open --label "auto-generated" --limit 500 --json number', cwd);
  const numbers = parseIssueList(raw);
  if (numbers == null) return null;
  return { numbers };
}

async function readIssueDetails(
  cwd: string,
  issueNumber: number,
  execSafeFn: ExecFn,
): Promise<{ title: string; body: string } | null> {
  const raw = await execSafeFn(`gh issue view ${issueNumber} --json number,title,body`, cwd);
  if (!raw.trim()) return null;

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }

  const details = parsed as IssueDetails;
  if (typeof details.title !== "string" || typeof details.body !== "string") return null;
  return { title: details.title, body: details.body };
}

export async function captureAutoGeneratedIssueSnapshot(
  cwd: string,
  execSafeFn: ExecFn,
): Promise<IssueSnapshot | null> {
  return readIssueSnapshot(cwd, execSafeFn);
}

export async function validateNewAutoGeneratedIssues(
  cwd: string,
  execSafeFn: ExecFn,
  beforeSnapshot: IssueSnapshot | null,
): Promise<string[]> {
  if (beforeSnapshot == null) {
    return ["could not capture the pre-creation `auto-generated` issue snapshot via `gh issue list`"];
  }

  const afterSnapshot = await readIssueSnapshot(cwd, execSafeFn);
  if (afterSnapshot == null) {
    return ["could not capture the post-creation `auto-generated` issue snapshot via `gh issue list`"];
  }

  const createdNumbers = [...afterSnapshot.numbers].filter((n) => !beforeSnapshot.numbers.has(n)).sort((a, b) => a - b);
  if (createdNumbers.length === 0) return [];

  const failures: string[] = [];
  for (const issueNumber of createdNumbers) {
    const details = await readIssueDetails(cwd, issueNumber, execSafeFn);
    if (details == null) {
      failures.push(`#${issueNumber}: could not read issue body via \`gh issue view\``);
      continue;
    }

    const errors = validateIssueDraft(details.body);
    if (errors.length === 0) continue;

    failures.push(`#${issueNumber} ${details.title}: ${errors.join("; ")}`);
  }

  return failures;
}
