import { describe, expect, it, vi } from "vitest";
import { captureAutoGeneratedIssueSnapshot, validateIssueDraft, validateNewAutoGeneratedIssues } from "./validation.js";

const VALID_ISSUE_BODY = `## Context
A small slice.

## Acceptance Criteria
- [ ] User sees the flow.

## Test Plan
- [ ] Trigger: GET /inventory returns the inventory screen.
- [ ] Boundary: invalid input shows an inline message.

## Implementation Hints
Keep the route wiring small.

## Structural Placement
- Owning boundary: \`src/inventory/\`
- Public entry point: \`src/inventory/index.js\`
- Files in scope: \`src/inventory/index.js\`, \`test/inventory/inventory.spec.js\`
- Out of scope: new unrelated files directly under \`src/\` or \`test/\`

## TDD Rehearsal
Planned red-green cycles:
1. Inventory route renders screen → \`test/inventory/inventory.spec.js\`

Totals:
- Tests: 1 / 15
- Files touched (estimate): 2 / 10
- Integration sites: 1 / 1

## Dependencies
None.
`;

const VALID_FEATURE_BODY = `## Context
A small slice.

## Acceptance Criteria
- [ ] User sees the flow.

## Test Plan
- [ ] Trigger: GET /inventory returns the inventory screen.
- [ ] Boundary: invalid input shows an inline message.

## Implementation Hints
Keep the route wiring small.

## Structural Placement
- Owning boundary: \`src/inventory/\`
- Public entry point: \`src/inventory/index.js\`
- Files in scope: \`src/inventory/index.js\`, \`test/inventory/inventory.spec.js\`
- Out of scope: new unrelated files directly under \`src/\` or \`test/\`

## TDD Rehearsal
Planned red-green cycles:
1. Inventory route renders screen → \`test/inventory/inventory.spec.js\`

Totals:
- Tests: 1 / 15
- Files touched (estimate): 2 / 10
- Integration sites: 1 / 1

## Dependencies
- #12
`;

describe("validateIssueDraft", () => {
  it("accepts an issue with structural placement and a non-root boundary", () => {
    expect(validateIssueDraft(VALID_ISSUE_BODY)).toEqual([]);
  });

  it("rejects generic roots as owning boundaries", () => {
    const errors = validateIssueDraft(
      VALID_ISSUE_BODY.replace("`src/inventory/`", "`packages/api/src/`").replace(
        "`src/inventory/index.js`",
        "`packages/api/src/app.js`",
      ),
    );

    expect(errors).toContain(
      "owning boundary `packages/api/src/` ends at generic root `src/`; choose a feature or domain folder beneath it",
    );
  });

  it("requires the first test-plan item to be a trigger test", () => {
    const errors = validateIssueDraft(VALID_ISSUE_BODY.replace("- [ ] Trigger:", "- [ ] Boundary:"));

    expect(errors).toContain("first `## Test Plan` item must start with `Trigger:`");
  });
});

describe("GitHub issue snapshots", () => {
  it("captures the current auto-generated issue set", async () => {
    const execSafeFn = vi.fn(async () => JSON.stringify([{ number: 10 }, { number: 11 }]));

    const snapshot = await captureAutoGeneratedIssueSnapshot("/tmp/project", execSafeFn);

    expect(snapshot?.numbers).toEqual(new Set([10, 11]));
  });

  it("validates newly created issues after generation", async () => {
    let listCalls = 0;
    const execSafeFn = vi.fn(async (cmd: string) => {
      if (cmd === "git ls-files") return "src/inventory/index.js\n";
      if (cmd.includes("gh issue list")) {
        listCalls += 1;
        return JSON.stringify(listCalls === 1 ? [{ number: 10 }] : [{ number: 10 }, { number: 12 }]);
      }
      if (cmd.includes("gh issue view 12")) {
        return JSON.stringify({ number: 12, title: "Create inventory home", body: VALID_ISSUE_BODY });
      }
      return "";
    });

    const before = await captureAutoGeneratedIssueSnapshot("/tmp/project", execSafeFn);
    const errors = await validateNewAutoGeneratedIssues("/tmp/project", execSafeFn, before);

    expect(errors).toEqual([]);
  });

  it("requires an explicit scaffold issue first on greenfield repos", async () => {
    let listCalls = 0;
    const execSafeFn = vi.fn(async (cmd: string) => {
      if (cmd === "git ls-files") return "PRD.md\nREADME.md\n";
      if (cmd.includes("gh issue list")) {
        listCalls += 1;
        return JSON.stringify(listCalls === 1 ? [] : [{ number: 12 }]);
      }
      if (cmd.includes("gh issue view 12")) {
        return JSON.stringify({ number: 12, title: "Create inventory home", body: VALID_ISSUE_BODY });
      }
      return "";
    });

    const before = await captureAutoGeneratedIssueSnapshot("/tmp/project", execSafeFn);
    const errors = await validateNewAutoGeneratedIssues("/tmp/project", execSafeFn, before);

    expect(errors).toContain(
      'greenfield repos must start with an explicit scaffold/bootstrap issue; lowest new issue #12 "Create inventory home" should use "scaffold" or "bootstrap" in the title',
    );
  });

  it("accepts a greenfield issue set rooted at a scaffold issue", async () => {
    let listCalls = 0;
    const execSafeFn = vi.fn(async (cmd: string) => {
      if (cmd === "git ls-files") return "PRD.md\nREADME.md\n";
      if (cmd.includes("gh issue list")) {
        listCalls += 1;
        return JSON.stringify(listCalls === 1 ? [] : [{ number: 12 }, { number: 13 }]);
      }
      if (cmd.includes("gh issue view 12")) {
        return JSON.stringify({
          number: 12,
          title: "Scaffold inventory app baseline",
          body: VALID_ISSUE_BODY,
        });
      }
      if (cmd.includes("gh issue view 13")) {
        return JSON.stringify({ number: 13, title: "Create inventory home", body: VALID_FEATURE_BODY });
      }
      return "";
    });

    const before = await captureAutoGeneratedIssueSnapshot("/tmp/project", execSafeFn);
    const errors = await validateNewAutoGeneratedIssues("/tmp/project", execSafeFn, before);

    expect(errors).toEqual([]);
  });
});
